// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: LvglLoRaMessenger

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Spinner1;
lv_obj_t *ui_TextInput;
lv_obj_t *ui_ButtonSend;
lv_obj_t *ui_Label2;
lv_obj_t *ui_TextMessages;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 300);
lv_obj_set_height( ui_Panel1, 220);
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xF2F2F2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -10 );
lv_obj_set_y( ui_Label1, -10 );
lv_label_set_text(ui_Label1,"LoRa Messenger");

ui_Spinner1 = lv_spinner_create(ui_Panel1,1000,90);
lv_obj_set_width( ui_Spinner1, 16);
lv_obj_set_height( ui_Spinner1, 16);
lv_obj_set_x( ui_Spinner1, 138 );
lv_obj_set_y( ui_Spinner1, -98 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_TextInput = lv_textarea_create(ui_Panel1);
lv_obj_set_width( ui_TextInput, 210);
lv_obj_set_height( ui_TextInput, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_TextInput, -35 );
lv_obj_set_y( ui_TextInput, 81 );
lv_obj_set_align( ui_TextInput, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextInput,"Input Message Here");
lv_textarea_set_one_line(ui_TextInput,true);
lv_obj_add_state( ui_TextInput, LV_STATE_FOCUSED );     /// States

ui_ButtonSend = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_ButtonSend, 60);
lv_obj_set_height( ui_ButtonSend, 32);
lv_obj_set_x( ui_ButtonSend, 110 );
lv_obj_set_y( ui_ButtonSend, 80 );
lv_obj_set_align( ui_ButtonSend, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSend, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSend, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 110 );
lv_obj_set_y( ui_Label2, 80 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Send");

ui_TextMessages = lv_textarea_create(ui_Panel1);
lv_obj_set_width( ui_TextMessages, 280);
lv_obj_set_height( ui_TextMessages, 140);
lv_obj_set_x( ui_TextMessages, 0 );
lv_obj_set_y( ui_TextMessages, -15 );
lv_obj_set_align( ui_TextMessages, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextMessages,"Message Log");
lv_obj_clear_flag( ui_TextMessages, LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_obj_set_style_text_font(ui_TextMessages, &ui_font_Cubic11, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
